package com.cryptolab.service;
import com.cryptolab.exception.VerificationException;
import com.cryptolab.model.*;
import org.junit.jupiter.api.Test;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
class ValidationServiceTest {
 @Test void requiresContainerAndProxyHealth(){ DockerService docker=mock(DockerService.class);ProxyService proxy=mock(ProxyService.class);ScenarioVerifier verifier=mock(ScenarioVerifier.class);ScenarioDefinition s=scenario();when(docker.inspectContainer("demo")).thenReturn(new ContainerInspection(true,true,true,"healthy",null,null,""));when(proxy.getRuntimeStatus()).thenReturn(Map.of("demo","UP"));when(verifier.supports(s)).thenReturn(true); ValidationService service=new ValidationService(docker,proxy,List.of(verifier));service.validateActivation(s);verify(verifier).verify(s); }
 @Test void rejectsUnhealthyContainer(){ DockerService docker=mock(DockerService.class);ProxyService proxy=mock(ProxyService.class);ScenarioDefinition s=scenario();when(docker.inspectContainer("demo")).thenReturn(ContainerInspection.unavailable("stopped"));ValidationService service=new ValidationService(docker,proxy,List.of());assertThrows(VerificationException.class,()->service.validateActivation(s)); }
 @Test void rejectsWhenMultipleBackendsAreReady(){ DockerService docker=mock(DockerService.class);ProxyService proxy=mock(ProxyService.class);ScenarioVerifier verifier=mock(ScenarioVerifier.class);ScenarioDefinition s=scenario();when(docker.inspectContainer("demo")).thenReturn(new ContainerInspection(true,true,true,"healthy",null,null,""));when(proxy.getRuntimeStatus()).thenReturn(Map.of("demo","UP","other","OPEN"));when(verifier.supports(s)).thenReturn(true);ValidationService service=new ValidationService(docker,proxy,List.of(verifier));assertThrows(VerificationException.class,()->service.validateActivation(s)); }
 @Test void rejectsWhenActiveBackendDoesNotMatchTarget(){ DockerService docker=mock(DockerService.class);ProxyService proxy=mock(ProxyService.class);ScenarioVerifier verifier=mock(ScenarioVerifier.class);ScenarioDefinition s=scenario();when(docker.inspectContainer("demo")).thenReturn(new ContainerInspection(true,true,true,"healthy",null,null,""));when(proxy.getRuntimeStatus()).thenReturn(Map.of("demo","MAINT","other","UP"));when(verifier.supports(s)).thenReturn(true);ValidationService service=new ValidationService(docker,proxy,List.of(verifier));assertThrows(VerificationException.class,()->service.validateActivation(s)); }
 static ScenarioDefinition scenario(){ScenarioDefinition s=new ScenarioDefinition();s.setId("demo");ScenarioRuntime r=new ScenarioRuntime();r.setContainerName("demo");r.setBackend("demo");s.setRuntime(r);ScenarioDefinition.Verification v=new ScenarioDefinition.Verification();v.setType("tls");s.setVerification(v);return s;}
}
